server:
  port: 8002
mybatis:
  type-aliases-package: com.ycc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: SPRINGCLOUD-PROVIDER-DEPT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.96.6.18:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ycc_Mysql1234
#Eureka 配置，服务注册到哪儿
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002 # 描述信息
    prefer-ip-address: true

#info 配置
info:
  app.name: ycc-springcloud
  company.name: amarsofts







